version: "3"

services:
  app:
    image: fortbrasil-frontend
    container_name: fortbrasil-frontend
    build: .
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    restart: always
    stdin_open: true
    tty: true
